[programs.localnet]
dapp_starter = "CkXsSzvGAz4Fkam5iqoYsxrCVRF7LvjjzCanbuZrzFnm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = ".wallets/hoangphuc.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
